version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/stable:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip3 install flake8 pytest --upgrade
      - run:
          name: Install latest ufl and fiat
          command: |
            pip install git+https://bitbucket.org/fenics-project/fiat.git --user
            pip install git+https://bitbucket.org/fenics-project/ufl.git --user
            pip install git+https://bitbucket.org/fenics-project/dijitso.git --user
      - run:
          name: Flake8 on source
          command:
            python3 -m flake8 source/
      - run:
          name: Flake8 on tests
          command: |
            python3 -m flake8 unit_tests/test*
            python3 -m flake8 tests/scalar_advection/
            python3 -m flake8 tests/single_phase_ns/
      - run:
          name: Installing DolfinParticles
          command: |
            cd source/cpp && cmake . && make
            echo $(pwd)
            cd ../.. && sudo python3 setup.py install
      - run:
          name: Running unit tests (serial)
          command: |
            cd unit_tests
            python3 -m pytest -v -s test*.py
      - run:
          name: Running unit tests (MPI)
          command: |
            cd unit_tests
            mpirun -n 3 python3 -m pytest -v -s test*.py
