version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/stable:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip3 install black pytest --upgrade
      - run:
          name: Install latest ufl and fiat
          command: |
            pip install git+https://bitbucket.org/fenics-project/fiat.git --user
            pip install git+https://bitbucket.org/fenics-project/ufl.git --user
            pip install git+https://bitbucket.org/fenics-project/dijitso.git --user
      - run:
          name: Check python formatting
          command: |
            black --check .
      - run:
          name: Installing DolfinParticles
          command: |
            cd source/cpp && cmake . && make
            echo $(pwd)
            cd ../.. && sudo python3 setup.py install
      - run:
          name: Running unit tests (serial)
          command: |
            cd unit_tests
            python3 -m pytest -v -s test*.py
      - run:
          name: Running unit tests (MPI)
          command: |
            cd unit_tests
            mpirun -n 3 python3 -m pytest -v -s test*.py
