version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/stable:latest
    steps:
      - checkout
      - run:
          name: Flake8 on source
          python3 -m flake8 source/*
      - run:
          name: Installing DolfinParticles
          command: |
            cd source/cpp && cmake . && make
            echo $(pwd)
            cd ../.. && sudo python3 setup.py install
      - run:
          name: Running unit tests
          command: |
            cd unit_tests
            python3 -m pytest -v -s test*
